title: PRCubeStars
theme: jekyll-theme-slate
copyright: PRCubeStars 2017
keywords: PRCubeStars, CubeSat, citizen science, students, scientists, engineers, computer science, teachers
gems:
  - jekyll-sitemap
